In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [18]:
# 导入美国各州的风险指数数据
danger_USA=pd.read_csv(r'D:\VSCodeWorkSpace\2024_C\dataprocess\dataset_process\danger_factor_USA.csv')
danger_USA

                   STATE  danger_factor
0                ALABAMA       4.927396
1                 ALASKA       0.036786
2         AMERICAN SAMOA       0.062924
3                ARIZONA       4.495644
4               ARKANSAS       4.541142
5             CALIFORNIA       5.031946
6               COLORADO       6.575992
7            CONNECTICUT       0.797677
8               DELAWARE       0.214908
9   DISTRICT OF COLUMBIA       0.098742
10               FLORIDA       3.355276
11               GEORGIA       3.941917
12                  GUAM       0.105518
13                HAWAII       1.577928
14                 IDAHO       0.396902
15              ILLINOIS       5.858664
16               INDIANA       2.291384
17                  IOWA       7.699903
18                KANSAS       8.985479
19              KENTUCKY       4.042594
20             LOUISIANA       3.815102
21                 MAINE       0.713456
22              MARYLAND       1.222652
23         MASSACHUSETTS       0.821878
24              MICHIGAN       1.201355
25             MINNESOTA       6.257502
26           MISSISSIPPI       5.283640
27              MISSOURI       6.496612
28               MONTANA       2.824782
29              NEBRASKA       9.376573
30                NEVADA       0.465634
31         NEW HAMPSHIRE       0.895450
32            NEW JERSEY       2.144240
33            NEW MEXICO       6.321394
34              NEW YORK       3.484027
35        NORTH CAROLINA       3.002904
36          NORTH DAKOTA       3.025169
37                  OHIO       2.126815
38              OKLAHOMA      10.830591
39                OREGON       0.197483
40          PENNSYLVANIA       3.354308
41           PUERTO RICO       1.057115
42          RHODE ISLAND       0.213940
43        SOUTH CAROLINA       1.962246
44          SOUTH DAKOTA       6.378509
45             TENNESSEE       4.116167
46                 TEXAS      26.904163
47                  UTAH       1.353340
48               VERMONT       0.369797
49        VIRGIN ISLANDS       0.056147
50              VIRGINIA       3.106486
51            WASHINGTON       0.285576
52         WEST VIRGINIA       1.487899
53             WISCONSIN       3.709584
54               WYOMING       1.606970

In [19]:
gdp_USA=pd.read_csv(r"D:\VSCodeWorkSpace\2024_C\dataprocess\dataset_process\gdp.csv")
# print(gdp_USA)
# 把gdp_USA数据中Q1-Q4列的数据对应行求和，保存到新的一列GDP中
gdp_USA['GDP'] = gdp_USA[['Q1', 'Q2', 'Q3', 'Q4p']].sum(axis=1)
gdp_USA.drop(['Q1', 'Q2', 'Q3', 'Q4p'], axis=1, inplace=True)
# print(gdp_USA)

# STATE转大写字母
gdp_USA['STATE'] = gdp_USA['STATE'].str.upper()
gdp_USA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STATE   60 non-null     object
 1   GDP     60 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.1+ KB

In [20]:
# 导入美国各州的字典
USA_state = pd.read_excel(r"D:\VSCodeWorkSpace\2024_C\data\State-Abbreviations.xlsx")
USA_state['State Name']=USA_state['State Name'].str.upper()
USA_state_dict=USA_state[['State Name']].reset_index(drop=True)
USA_state_dict

        State Name
0          ALABAMA
1           ALASKA
2          ARIZONA
3         ARKANSAS
4       CALIFORNIA
5         COLORADO
6      CONNECTICUT
7         DELAWARE
8          FLORIDA
9          GEORGIA
10          HAWAII
11           IDAHO
12        ILLINOIS
13         INDIANA
14            IOWA
15          KANSAS
16        KENTUCKY
17       LOUISIANA
18           MAINE
19        MARYLAND
20   MASSACHUSETTS
21        MICHIGAN
22       MINNESOTA
23     MISSISSIPPI
24        MISSOURI
25         MONTANA
26        NEBRASKA
27          NEVADA
28   NEW HAMPSHIRE
29      NEW JERSEY
30      NEW MEXICO
31        NEW YORK
32  NORTH CAROLINA
33    NORTH DAKOTA
34            OHIO
35        OKLAHOMA
36          OREGON
37    PENNSYLVANIA
38    RHODE ISLAND
39  SOUTH CAROLINA
40    SOUTH DAKOTA
41       TENNESSEE
42           TEXAS
43            UTAH
44         VERMONT
45        VIRGINIA
46      WASHINGTON
47   WEST VIRGINIA
48       WISCONSIN
49         WYOMING

In [21]:
# 保留danger_USA['STATE']与USA_state_dic['State Name']的公共部分
danger_USA = danger_USA[danger_USA['STATE'].isin(USA_state_dict['State Name'])]
danger_USA.reset_index(drop=True, inplace=True)
USA_state_dict.info()
gdp_USA.info()
# 去掉gdp_USA中不在字典里的行
gdp_USA['STATE'] = gdp_USA['STATE'].str.strip()
gdp_USA = gdp_USA[gdp_USA['STATE'].isin(USA_state_dict['State Name'])]
gdp_USA.reset_index(drop=True, inplace=True)
gdp_USA.info()
# 找到不再STATE里的州，并去掉

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State Name  50 non-null     object
dtypes: object(1)
memory usage: 528.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STATE   60 non-null     object
 1   GDP     60 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STATE   50 non-null     object
 1   GDP     50 non-null     int64
dtypes: int64(1), object(1)
memory usage: 928.0+ bytes

In [22]:
# 导入人口数据
population_USA = pd.read_csv(r"D:\VSCodeWorkSpace\2024_C\dataprocess\dataset_process\population.csv")
population_USA['STATE']=population_USA['STATE'].str.upper()

In [23]:
population_USA = population_USA[population_USA['STATE'].isin(USA_state_dict['State Name'])]
population_USA.reset_index(drop=True, inplace=True)
population_USA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Population  50 non-null     int64
 1   STATE       50 non-null     object
dtypes: int64(1), object(1)
memory usage: 928.0+ bytes

In [24]:
#合并gdp danger population数据
USA_data = pd.merge(danger_USA, gdp_USA, on='STATE', how='left')
USA_data = pd.merge(USA_data, population_USA, on='STATE', how='left')
# 转化为浮点型

USA_data['GDP']=USA_data['GDP'].astype(float)
USA_data['Population']=USA_data['Population'].astype(float)
USA_data

             STATE  danger_factor         GDP  Population
0          ALABAMA       4.927396    899481.0   5024279.0
1           ALASKA       0.036786    200986.0    733391.0
2          ARIZONA       4.495644   1489844.0   7151502.0
3         ARKANSAS       4.541142    516295.0   3011524.0
4       CALIFORNIA       5.031946  12367486.0  39538223.0
5         COLORADO       6.575992   1560395.0   5773714.0
6      CONNECTICUT       0.797677   1123600.0   3605944.0
7         DELAWARE       0.214908    302050.0    989948.0
8          FLORIDA       3.355276   4383553.0  21538187.0
9          GEORGIA       3.941917   2476961.0  10711908.0
10          HAWAII       1.577928    359425.0   1455271.0
11           IDAHO       0.396902    336129.0   1839106.0
12        ILLINOIS       5.858664   3454066.0  12812508.0
13         INDIANA       2.291384   1490547.0   6785528.0
14            IOWA       7.699903    770841.0   3190369.0
15          KANSAS       8.985479    693192.0   2937880.0
16        KENTUCKY       4.042594    840096.0   4505836.0
17       LOUISIANA       3.815102    967963.0   4657757.0
18           MAINE       0.713456    264783.0   1362359.0
19        MARYLAND       1.222652   1690906.0   6177224.0
20   MASSACHUSETTS       0.821878   2336155.0   7029917.0
21        MICHIGAN       1.201355   2063713.0  10077331.0
22       MINNESOTA       6.257502   1497407.0   5706494.0
23     MISSISSIPPI       5.283640    456802.0   2961279.0
24        MISSOURI       6.496612   1286836.0   6154913.0
25         MONTANA       2.824782    205955.0   1084225.0
26        NEBRASKA       9.376573    515235.0   1961504.0
27          NEVADA       0.465634    690390.0   3104614.0
28   NEW HAMPSHIRE       0.895450    340436.0   1377529.0
29      NEW JERSEY       2.144240   2476246.0   9288994.0
30      NEW MEXICO       6.321394    401241.0   2117522.0
31        NEW YORK       3.484027   6796179.0  20201249.0
32  NORTH CAROLINA       3.002904   2344546.0  10439388.0
33    NORTH DAKOTA       3.025169    216132.0    779094.0
34            OHIO       2.126815   2700148.0  11799448.0
35        OKLAHOMA      10.830591    746326.0   3959353.0
36          OREGON       0.197483   1001834.0   4237256.0
37    PENNSYLVANIA       3.354308   3120704.0  13002700.0
38    RHODE ISLAND       0.213940    240898.0   1097379.0
39  SOUTH CAROLINA       1.962246    966755.0   5118425.0
40    SOUTH DAKOTA       6.378509    219408.0    886667.0
41       TENNESSEE       4.116167   1457944.0   6910840.0
42           TEXAS      26.904163   7038937.0  29145505.0
43            UTAH       1.353340    779943.0   3271616.0
44         VERMONT       0.369797    131188.0    643077.0
45        VIRGINIA       3.106486   2207041.0   8631393.0
46      WASHINGTON       0.285576   2474820.0   7705281.0
47   WEST VIRGINIA       1.487899    294837.0   1793716.0
48       WISCONSIN       3.709584   1354714.0   5893718.0
49         WYOMING       1.606970    144966.0    576851.0

In [25]:
import pandas as pd
from topsispy import topsis

# 假设data_USA包含'GDP'、'population'和'danger_data'列
# 指定指标权重
weights = [0.3, 0.2, 0.5]

# 指定指标的优劣类型（"max"表示越大越好，"min"表示越小越好）
criteria = ["max", "max", "max"]

# 进行TOPSIS得分计算
a=USA_data[['GDP', 'Population', 'danger_factor']]
# print(a)
# 去掉列名
# a = a.drop(['GDP', 'Population', 'danger_factor'], axis=1)
# 将dataframe的值（除列名）转化为一个矩阵
a = a.values
# print(a)
result = topsis(a, weights, criteria)
# print(result)
b=pd.DataFrame(result[1])
# print(b)

# 将得分结果添加到原始DataFrame中
USA_data['topsis_score'] = b

# 按TOPSIS得分降序排列
topsis_USA = USA_data.sort_values(by='topsis_score', ascending=False)
topsis_USA.reset_index(drop=True, inplace=True)
# 打印结果
print(topsis_USA[['STATE', 'topsis_score']])
topsis_USA

             STATE  topsis_score
0           ALASKA      0.997054
1     RHODE ISLAND      0.992109
2         DELAWARE      0.990847
3          VERMONT      0.989682
4            IDAHO      0.983597
5            MAINE      0.977688
6    NEW HAMPSHIRE      0.971593
7           NEVADA      0.968867
8           OREGON      0.957516
9    WEST VIRGINIA      0.953901
10         WYOMING      0.951714
11          HAWAII      0.951156
12     CONNECTICUT      0.950025
13            UTAH      0.948267
14  SOUTH CAROLINA      0.924747
15        MARYLAND      0.919303
16         MONTANA      0.914567
17    NORTH DAKOTA      0.908633
18   MASSACHUSETTS      0.902096
19         INDIANA      0.901947
20      WASHINGTON      0.899373
21        MICHIGAN      0.894988
22       LOUISIANA      0.875487
23      NEW JERSEY      0.873305
24       WISCONSIN      0.870954
25        KENTUCKY      0.870577
26        VIRGINIA      0.862948
27        ARKANSAS      0.860599
28            OHIO      0.859383
29  NORTH CAROLINA      0.856673
30       TENNESSEE      0.856265
31         ARIZONA      0.845006
32         ALABAMA      0.843756
33     MISSISSIPPI      0.839323
34         GEORGIA      0.832513
35    PENNSYLVANIA      0.823652
36    SOUTH DAKOTA      0.810405
37      NEW MEXICO      0.810355
38       MINNESOTA      0.798344
39        MISSOURI      0.793385
40        COLORADO      0.788504
41            IOWA      0.767735
42         FLORIDA      0.765848
43        ILLINOIS      0.761788
44          KANSAS      0.732878
45        NEBRASKA      0.724469
46        NEW YORK      0.710092
47        OKLAHOMA      0.681759
48      CALIFORNIA      0.541329
49           TEXAS      0.197535

             STATE  danger_factor         GDP  Population  topsis_score
0           ALASKA       0.036786    200986.0    733391.0      0.997054
1     RHODE ISLAND       0.213940    240898.0   1097379.0      0.992109
2         DELAWARE       0.214908    302050.0    989948.0      0.990847
3          VERMONT       0.369797    131188.0    643077.0      0.989682
4            IDAHO       0.396902    336129.0   1839106.0      0.983597
5            MAINE       0.713456    264783.0   1362359.0      0.977688
6    NEW HAMPSHIRE       0.895450    340436.0   1377529.0      0.971593
7           NEVADA       0.465634    690390.0   3104614.0      0.968867
8           OREGON       0.197483   1001834.0   4237256.0      0.957516
9    WEST VIRGINIA       1.487899    294837.0   1793716.0      0.953901
10         WYOMING       1.606970    144966.0    576851.0      0.951714
11          HAWAII       1.577928    359425.0   1455271.0      0.951156
12     CONNECTICUT       0.797677   1123600.0   3605944.0      0.950025
13            UTAH       1.353340    779943.0   3271616.0      0.948267
14  SOUTH CAROLINA       1.962246    966755.0   5118425.0      0.924747
15        MARYLAND       1.222652   1690906.0   6177224.0      0.919303
16         MONTANA       2.824782    205955.0   1084225.0      0.914567
17    NORTH DAKOTA       3.025169    216132.0    779094.0      0.908633
18   MASSACHUSETTS       0.821878   2336155.0   7029917.0      0.902096
19         INDIANA       2.291384   1490547.0   6785528.0      0.901947
20      WASHINGTON       0.285576   2474820.0   7705281.0      0.899373
21        MICHIGAN       1.201355   2063713.0  10077331.0      0.894988
22       LOUISIANA       3.815102    967963.0   4657757.0      0.875487
23      NEW JERSEY       2.144240   2476246.0   9288994.0      0.873305
24       WISCONSIN       3.709584   1354714.0   5893718.0      0.870954
25        KENTUCKY       4.042594    840096.0   4505836.0      0.870577
26        VIRGINIA       3.106486   2207041.0   8631393.0      0.862948
27        ARKANSAS       4.541142    516295.0   3011524.0      0.860599
28            OHIO       2.126815   2700148.0  11799448.0      0.859383
29  NORTH CAROLINA       3.002904   2344546.0  10439388.0      0.856673
30       TENNESSEE       4.116167   1457944.0   6910840.0      0.856265
31         ARIZONA       4.495644   1489844.0   7151502.0      0.845006
32         ALABAMA       4.927396    899481.0   5024279.0      0.843756
33     MISSISSIPPI       5.283640    456802.0   2961279.0      0.839323
34         GEORGIA       3.941917   2476961.0  10711908.0      0.832513
35    PENNSYLVANIA       3.354308   3120704.0  13002700.0      0.823652
36    SOUTH DAKOTA       6.378509    219408.0    886667.0      0.810405
37      NEW MEXICO       6.321394    401241.0   2117522.0      0.810355
38       MINNESOTA       6.257502   1497407.0   5706494.0      0.798344
39        MISSOURI       6.496612   1286836.0   6154913.0      0.793385
40        COLORADO       6.575992   1560395.0   5773714.0      0.788504
41            IOWA       7.699903    770841.0   3190369.0      0.767735
42         FLORIDA       3.355276   4383553.0  21538187.0      0.765848
43        ILLINOIS       5.858664   3454066.0  12812508.0      0.761788
44          KANSAS       8.985479    693192.0   2937880.0      0.732878
45        NEBRASKA       9.376573    515235.0   1961504.0      0.724469
46        NEW YORK       3.484027   6796179.0  20201249.0      0.710092
47        OKLAHOMA      10.830591    746326.0   3959353.0      0.681759
48      CALIFORNIA       5.031946  12367486.0  39538223.0      0.541329
49           TEXAS      26.904163   7038937.0  29145505.0      0.197535

In [26]:
#根据topsisscore划分等级，高于0.85为优，介于0.7-0.85为中，低于0.7为差。将结果映射到topsis_score中
topsis_USA['topsis_score_level'] = topsis_USA['topsis_score'].apply(
    lambda x: '优' if x >= 0.9 
    else '中' if x < 0.9 and x >= 0.8 
    else '差')
topsis_USA

,STATE,danger_factor,GDP,Population,topsis_score,topsis_score_level
0,ALASKA,0.036786,200986.0,733391.0,0.997054,优
1,RHODE ISLAND,0.213940,240898.0,1097379.0,0.992109,优
2,DELAWARE,0.214908,302050.0,989948.0,0.990847,优
3,VERMONT,0.369797,131188.0,643077.0,0.989682,优
4,IDAHO,0.396902,336129.0,1839106.0,0.983597,优
5,MAINE,0.713456,264783.0,1362359.0,0.977688,优
6,NEW HAMPSHIRE,0.895450,340436.0,1377529.0,0.971593,优
7,NEVADA,0.465634,690390.0,3104614.0,0.968867,优
8,OREGON,0.197483,1001834.0,4237256.0,0.957516,优
9,WEST VIRGINIA,1.487899,294837.0,1793716.0,0.953901,优
10,WYOMING,1.606970,144966.0,576851.0,0.951714,优
11,HAWAII,1.577928,359425.0,1455271.0,0.951156,优
12,CONNECTICUT,0.797677,1123600.0,3605944.0,0.950025,优
13,UTAH,1.353340,779943.0,3271616.0,0.948267,优
14,SOUTH CAROLINA,1.962246,966755.0,5118425.0,0.924747,优
15,MARYLAND,1.222652,1690906.0,6177224.0,0.919303,优
16,MONTANA,2.824782,205955.0,1084225.0,0.914567,优
17,NORTH DAKOTA,3.025169,216132.0,779094.0,0.908633,优
18,MASSACHUSETTS,0.821878,2336155.0,7029917.0,0.902096,优
19,INDIANA,2.291384,1490547.0,6785528.0,0.901947,优
20,WASHINGTON,0.285576,2474820.0,7705281.0,0.899373,中
21,MICHIGAN,1.201355,2063713.0,10077331.0,0.894988,中
22,LOUISIANA,3.815102,967963.0,4657757.0,0.875487,中
23,NEW JERSEY,2.144240,2476246.0,9288994.0,0.873305,中
24,WISCONSIN,3.709584,1354714.0,5893718.0,0.870954,中
25,KENTUCKY,4.042594,840096.0,4505836.0,0.870577,中
26,VIRGINIA,3.106486,2207041.0,8631393.0,0.862948,中
27,ARKANSAS,4.541142,516295.0,3011524.0,0.860599,中
28,OHIO,2.126815,2700148.0,11799448.0,0.859383,中
29,NORTH CAROLINA,3.002904,2344546.0,10439388.0,0.856673,中
30,TENNESSEE,4.116167,1457944.0,6910840.0,0.856265,中
31,ARIZONA,4.495644,1489844.0,7151502.0,0.845006,中
32,ALABAMA,4.927396,899481.0,5024279.0,0.843756,中
33,MISSISSIPPI,5.283640,456802.0,2961279.0,0.839323,中
34,GEORGIA,3.941917,2476961.0,10711908.0,0.832513,中
35,PENNSYLVANIA,3.354308,3120704.0,13002700.0,0.823652,中
36,SOUTH DAKOTA,6.378509,219408.0,886667.0,0.810405,中
37,NEW MEXICO,6.321394,401241.0,2117522.0,0.810355,中
38,MINNESOTA,6.257502,1497407.0,5706494.0,0.798344,差
39,MISSOURI,6.496612,1286836.0,6154913.0,0.793385,差
40,COLORADO,6.575992,1560395.0,5773714.0,0.788504,差
41,IOWA,7.699903,770841.0,3190369.0,0.767735,差
42,FLORIDA,3.355276,4383553.0,21538187.0,0.765848,差
43,ILLINOIS,5.858664,3454066.0,12812508.0,0.761788,差
44,KANSAS,8.985479,693192.0,2937880.0,0.732878,差
45,NEBRASKA,9.376573,515235.0,1961504.0,0.724469,差
46,NEW YORK,3.484027,6796179.0,20201249.0,0.710092,差
47,OKLAHOMA,10.830591,746326.0,3959353.0,0.681759,差
48,CALIFORNIA,5.031946,12367486.0,39538223.0,0.541329,差
49,TEXAS,26.904163,7038937.0,29145505.0,0.197535,差

In [27]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 假设你的DataFrame为df，包含列STATE, danger_factor, GDP, Population, topsis_score, topsis_score_level
df = topsis_USA

# 将特征和目标变量分离
features = df[['danger_factor', 'GDP', 'Population']]
target = df['topsis_score_level']

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# 创建支持向量机模型
svm_model = SVC()

# 使用训练集训练模型
svm_model.fit(X_train, y_train)

# 在测试集上进行预测
y_pred = svm_model.predict(X_test)
print(y_pred)
# 计算准确率
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

TX= pd.DataFrame({'danger_factor': [26.9], 'GDP': [7038937.0], 'Population': [29145505.0]})
UNNKOWN=pd.DataFrame({'danger_factor': [5.858664], 'GDP': [3454066.0], 'Population': [12812508.0]})
# 5.858664	3454066.0	12812508.0
svm_prediction = svm_model.predict(TX)
svm_prediction_1 = svm_model.predict(UNNKOWN)
print("Texas topsis score prediction:", svm_prediction)
print("Unknown topsis score prediction:", svm_prediction_1)

['优' '中' '中' '优' '优' '差' '中' '优' '优' '中']
Accuracy: 0.5
Texas topsis score prediction: ['差']
Unknown topsis score prediction: ['中']

In [28]:
# import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder


# 假设你的DataFrame为df，包含列STATE, danger_factor, GDP, Population, topsis_score, topsis_score_level
df=topsis_USA

# 将特征和目标变量分离
features = df[['danger_factor', 'GDP', 'Population']]
target = df['topsis_score_level']

# 数据预处理：标准化特征
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)
# print(scaled_features)
# print(target)
target = target.values
# 创建LabelEncoder对象并进行标签编码
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(target)

print(encoded_labels)
# 输出: [0 1 0 2 1]

print(target)

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(scaled_features, encoded_labels, test_size=0.2, random_state=42)

# 创建神经网络模型
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(3,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# 编译模型
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 训练模型
model.fit(X_train, y_train, epochs=10, batch_size=32)

# 在测试集上评估模型
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Accuracy:", accuracy)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 2 2 2 2 2 2 2 2 2 2 2 2]
['优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优' '优'
 '优' '优' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中' '中'
 '中' '中' '差' '差' '差' '差' '差' '差' '差' '差' '差' '差' '差' '差']
Epoch 1/10
2/2 [==============================] - 0s 2ms/step - loss: 0.5008 - accuracy: 0.4250
Epoch 2/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4878 - accuracy: 0.4250
Epoch 3/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4717 - accuracy: 0.4250
Epoch 4/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4629 - accuracy: 0.4250
Epoch 5/10
2/2 [==============================] - 0s 1000us/step - loss: 0.4514 - accuracy: 0.4250
Epoch 6/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4400 - accuracy: 0.4250
Epoch 7/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.4250
Epoch 8/10
2/2 [==============================] - 0s 1ms/step - loss: 0.4206 - accuracy: 0.4250
Epoch 9/10
2/2 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.4250
Epoch 10/10
2/2 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.4250
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_test_function.<locals>.test_function at 0x000001BA941E4B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 [==============================] - 0s 61ms/step - loss: 0.0789 - accuracy: 0.3000
Loss: 0.07887110859155655
Accuracy: 0.30000001192092896